---
title: "Salary Statistics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
#1. Extract salaires from salary table and create histogram
query<-"SELECT salary
FROM Salaries"
result<-sqldf(query)

ggplot()+
  geom_histogram(data=result, aes(x=salary), color="red", bins=15)+
  ggtitle("MLB Salary Distribution")+
  xlab("Player Salaries")+
  ylab("Number of Players")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#2. Extract year & avg. salary for the year and make time-series plot.
query<-"SELECT yearID, avg(salary) AS Avg_Salary
FROM Salaries
GROUP BY yearID"
result2<-sqldf(query)

ggplot()+
  geom_line(data=result2,aes(x=yearID, y=Avg_Salary), size=1.1, color="light blue")+
  geom_point(data=result2,aes(x=yearID, y=Avg_Salary),size=1, color="black")+
  ggtitle("Average Annual MLB Salary")+
  xlab("Year")+
  ylab("Average Salary")

```

### Chart C

```{r}
#3. Extract salary & homeruns and make a scatterplot with salary on the x-axis. HR >= 10
query<-"SELECT salary, HR
FROM Batting INNER JOIN Salaries
ON Batting.playerID=Salaries.playerID AND Batting.yearID=Salaries.yearID
WHERE HR>=10"
result3<-sqldf(query)

ggplot()+
  geom_point(data=result3,aes(x=salary, y=HR), size=1, color ="dark green")+
  ggtitle("MLB Salary vs. Homerun Production")+
  xlab("Salary")+
  ylab("Homerun")
```

